# Generated by Django 5.0 on 2024-04-23 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_resume_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='title',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='title',
            field=models.CharField(default='untitled', max_length=100),
            preserve_default=False,
        ),
    ]
