# Generated by Django 5.0 on 2024-04-23 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0003_resume_title_skill_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='name',
        ),
        migrations.AddField(
            model_name='skill',
            name='skills',
            field=models.CharField(choices=[('*', 'Beginner'), ('**', 'Intermediate'), ('***', 'Advance')], default='untitled', max_length=3),
            preserve_default=False,
        ),
    ]
