# Generated by Django 5.0 on 2024-04-25 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0004_remove_skill_name_skill_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skills',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advance', 'Advance')], max_length=12),
        ),
    ]
