# Generated by Django 5.0 on 2024-04-25 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0005_alter_skill_skills'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='file',
            new_name='resume',
        ),
    ]
