# Generated by Django 5.0 on 2024-04-25 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0007_rename_resume_resume_resumes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='resumes',
            new_name='file',
        ),
    ]
