# Generated by Django 5.0 on 2024-04-26 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0008_rename_resumes_resume_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('current', models.CharField(choices=[('Current', 'Notice Period')], max_length=12)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
