# Generated by Django 5.0 on 2024-04-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0010_alter_experience_current'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='current',
            field=models.CharField(choices=[('Working', 'Finished')], max_length=52),
        ),
    ]
