# Generated by Django 5.0 on 2024-04-27 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0011_alter_experience_current'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=100)),
                ('degree', models.CharField(choices=[('Bachelor', 'Bachelor'), ('Master', 'Master'), ('PhD', 'PhD'), ('Diploma', 'Diploma'), ('Certificate', 'Certificate')], max_length=20)),
                ('specialization', models.CharField(max_length=100)),
                ('start_year', models.PositiveIntegerField()),
                ('end_year', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='experience',
            name='current',
            field=models.CharField(choices=[('Working', 'Working'), ('Finished', 'Finished')], max_length=12),
        ),
    ]
